server:
  port: 8000

keycloak:
  auth-server-url: http://localhost:8180/auth
  realm: Tour
  resource: tour-app
  bearer-only: true
  ssl-required: external
  use-resource-role-mappings: true
  credentials.secret: b5afeb36-73d2-4c85-84ee-aeb8d58abccf

spring:
  rabbitmq:
    addresses: ${CLOUDAMQP_URL}

  datasource:
    url: jdbc:postgresql://192.168.0.100:5432/tour_api
    username: postgres
    password: 3262015Aze3262!

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

  mvc:
    format:
      date: dd.MM.yyyy
      time: HH:mm:ss
      date-time: dd.MM.yyyy HH:mm:ss

  mail:
    host: smtp.gmail.com
    port: 587
    username: subscriptonmanagmentmailsender@gmail.com
    password: 32620155
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
    properties.mail.properties.mail.transport.protocol: smtp
    properties.mail.debug: true

auth:
  mails:
    verification:
      subject: Tour.tap account verification
      context: Please click this link (%s) to verify your account.
      urls:
        verification-url: http://localhost:8000/api/v1/auth/verify?token=%s&username=%s
    reset-password:
      subject: Tour.tap account reset password
      context: Please click this link (%s) to reset your account password.
      urls:
        reset-url: http://localhost:8000/api/v1/auth/resetPassword?token=%s&username=%s
  users:
    admin:
      username: parvinyy@code.edu.az
      password: 3262015

app:
  start-time: "09:00:00"
  end-time: "19:00:00"
  deadline: 8
  expiration-check-duration: PT1H