server:
  port: 8000

keycloak:
  auth-server-url: ${KEYCLOAK_SERVER_URL}
  realm: Tour
  resource: tour-app
  bearer-only: true
  ssl-required: external
  use-resource-role-mappings: true
  credentials.secret: ${KEYCLOAK_SECRET}

spring:
  rabbitmq:
    addresses: ${CLOUDAMQP_URL}

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

  mvc:
    format:
      date: dd.MM.yyyy
      time: HH:mm:ss
      date-time: dd.MM.yyyy HH:mm:ss

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_SENDER_USERNAME}
    password: ${MAIL_SENDER_PASSWORD}
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
    properties.mail.properties.mail.transport.protocol: smtp
    properties.mail.debug: true

auth:
  mails:
    verification:
      subject: Tour.tap account verification
      context: Please click this link (%s) to verify your account.
      urls:
        verification-url: http://localhost:8000/api/v1/auth/verify?token=%s&username=%s
    reset-password:
      subject: Tour.tap account reset password
      context: Please click this link (%s) to reset your account password.
      urls:
        reset-url: http://localhost:8000/api/v1/auth/resetPassword?token=%s&username=%s
  users:
    admin:
      username: ${KEYCLOAK_CLI_USERNAME}
      password: ${KEYCLOAK_CLI_PASSWORD}

app:
  start-time: "09:00:00"
  end-time: "23:00:00"
  deadline: 8
  expiration-check-duration: PT1H