server:
  port: 8000

keycloak:
  auth-server-url: http://localhost:8180/auth
  realm: Tour
  resource: tour-app
  bearer-only: true
  ssl-required: external
  use-resource-role-mappings: true
  credentials.secret: b5afeb36-73d2-4c85-84ee-aeb8d58abccf

spring:
  datasource:
    url: jdbc:postgresql://192.168.0.100:5432/test
    username: postgres
    password: 3262015Aze3262!

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: subscriptonmanagmentmailsender@gmail.com
    password: 32620155
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
    properties.mail.properties.mail.transport.protocol: smtp
    properties.mail.debug: true